# Generated by Django 4.1 on 2022-08-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetpeople',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet_people1', to='general_user.generaluser'),
        ),
        migrations.AlterField(
            model_name='meetpeople',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet_people2', to='general_user.generaluser'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_user.generaluser'),
        ),
    ]
